"use client";

import { useState } from "react";
import Navbar from "@/components/Navbar";
import AudioUpload from "@/components/AudioUpload";
import ResultDisplay from "@/components/ResultDisplay";
import ConfidenceMeter from "@/components/ConfidenceMeter";
import AudioVisualizations from "@/components/AudioVisualizations";
import {
  predictAudio,
  getVisualizations,
  type PredictionResult,
  type Visualizations,
} from "@/lib/api";

export default function Home() {
  const [showViz, setShowViz] = useState(true);
  const [showTech, setShowTech] = useState(false);

  const [file, setFile] = useState<File | null>(null);
  const [audioUrl, setAudioUrl] = useState<string | null>(null);
  const [result, setResult] = useState<PredictionResult | null>(null);
  const [vizData, setVizData] = useState<Visualizations | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleFile = async (f: File) => {
    setFile(f);
    setResult(null);
    setVizData(null);
    setError(null);
    setAudioUrl(URL.createObjectURL(f));
    setLoading(true);

    try {
      const [pred, viz] = await Promise.allSettled([
        predictAudio(f),
        showViz ? getVisualizations(f) : Promise.resolve(null),
      ]);

      if (pred.status === "fulfilled") {
        setResult(pred.value);
      } else {
        setError("Prediction failed. Please try another file.");
      }

      if (viz.status === "fulfilled" && viz.value) {
        setVizData(viz.value);
      }
    } catch {
      setError("Something went wrong. Is the server running?");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Navbar
        showVisualizations={showViz}
        onToggleVisualizations={setShowViz}
        showTechnical={showTech}
        onToggleTechnical={setShowTech}
      />

      <main className="flex-1 p-6 lg:p-10 max-w-5xl mx-auto w-full space-y-8">
        {/* Upload + Results grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {/* Left: Upload */}
          <div className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-200">Upload Audio</h2>
            <AudioUpload onFileSelected={handleFile} disabled={loading} />
            {audioUrl && (
              <audio controls src={audioUrl} className="w-full mt-3" />
            )}
          </div>

          {/* Right: Results */}
          <div className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-200">Analysis Results</h2>

            {loading && (
              <div className="flex items-center justify-center py-12 text-gray-400">
                <svg
                  className="animate-spin h-6 w-6 mr-3 text-blue-400"
                  viewBox="0 0 24 24"
                  fill="none"
                >
                  <circle
                    className="opacity-25"
                    cx="12"
                    cy="12"
                    r="10"
                    stroke="currentColor"
                    strokeWidth="4"
                  />
                  <path
                    className="opacity-75"
                    fill="currentColor"
                    d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z"
                  />
                </svg>
                Analyzing audio...
              </div>
            )}

            {error && (
              <div className="bg-red-900/30 border border-red-700 rounded-lg p-4 text-red-300 text-sm">
                {error}
              </div>
            )}

            {result && !loading && (
              <div className="space-y-5">
                <ResultDisplay result={result} />
                <ConfidenceMeter result={result} showTechnical={showTech} />
                <div className="bg-yellow-900/30 border border-yellow-700/50 rounded-lg p-3 text-yellow-300/90 text-xs leading-relaxed">
                  <strong>Note:</strong> This model was trained on real music and AI audio from MusicGen, MusicLDM, AudioLDM2, Stable Audio Open, Mustango, and SunoAI. Audio generated by other AI tools may not be accurately detected.
                </div>
              </div>
            )}

            {!result && !loading && !error && (
              <div className="text-gray-500 bg-gray-800/50 rounded-lg p-8 text-center">
                Upload an audio file to begin analysis
              </div>
            )}
          </div>
        </div>

        {/* Visualizations */}
        {showViz && vizData && !loading && (
          <div className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-200">
              Audio Visualizations
            </h2>
            <AudioVisualizations data={vizData} />
          </div>
        )}
      </main>

      <footer className="text-center text-xs text-gray-600 py-4">
        Vocaluity — Bimsara Rathnayake
      </footer>
    </div>
  );
}
